### ISSUE TITLE
Named connection string not found in .Net5 WPF application

### ISSUE THREAD

**Issue by rtbsoft** [efcore/EFCore.ConfigurationManager#3] opened 2021-08-19 16:18 UTC
the project file (in part):

~~~~xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.ConfigurationManager" Version="1.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.9" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
  </ItemGroup>
~~~~

the app.config:

~~~~ xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <connectionStrings>
    <!-- adjust this connection string as needed for your environment -->
    <add connectionString="Server=.\SQLEXPRESS;Database=NorthWind;Trusted_Connection=True;" name="conn"/>
  </connectionStrings>
</configuration>
~~~~

the C# code:

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseConfigurationManager().UseSqlServer("name=conn");
        }

the command line:

dotnet ef migrations add base

the error:

System.InvalidOperationException: A named connection string was used, but the name 'conn' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.
   at EntityFrameworkCore.ConfigurationManager.ConfigrationManagerConnectionStringResolver.ResolveConnectionString(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection..ctor(RelationalConnectionDependencies dependencies)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection..ctor(RelationalConnectionDependencies dependencies)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

I guess I thought that your library would deal with this translation?
### 
The code does run, so it does use the name properly at runtime. Just not at design time.

> ``

**Comment by bricelam** [comment] 2021-09-16 18:47
Duplicate of #2?

**Closed as completed** 2021-11-18 20:01 UTC
Labels: duplicate
